In [8]:
import torch

# Tensor和操作

In [31]:
# 未初始化
x = torch.Tensor(5, 3)
# 随机初始化
x = torch.rand(5, 3)
print x
print x.size()


 0.1174  0.1588  0.5416
 0.7464  0.8802  0.3231
 0.2365  0.1080  0.1693
 0.3078  0.3747  0.8582
 0.7078  0.4216  0.1078
[torch.FloatTensor of size 5x3]

torch.Size([5, 3])


In [32]:
x = torch.Tensor([1, 2])
print x


 1
 2
[torch.FloatTensor of size 2]



In [26]:
y = torch.rand(5, 3)
print (x+y)
z = x+y
print z


 1.3010  0.7798  1.4748
 1.2550  0.8332  1.3546
 0.4224  0.8668  0.0814
 1.1755  1.3665  1.3029
 1.5003  0.6164  1.0745
[torch.FloatTensor of size 5x3]


 1.3010  0.7798  1.4748
 1.2550  0.8332  1.3546
 0.4224  0.8668  0.0814
 1.1755  1.3665  1.3029
 1.5003  0.6164  1.0745
[torch.FloatTensor of size 5x3]



In [14]:
print (torch.add(x, y))


 0.6799  0.1859  1.3768
 1.6563  0.6146  1.3275
 0.4393  0.9025  0.8688
 0.6988  1.1053  1.6277
 0.9798  0.6091  1.0265
[torch.FloatTensor of size 5x3]



In [15]:
# 带有返回值
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)
print result


 0.6799  0.1859  1.3768
 1.6563  0.6146  1.3275
 0.4393  0.9025  0.8688
 0.6988  1.1053  1.6277
 0.9798  0.6091  1.0265
[torch.FloatTensor of size 5x3]



In [16]:
# 直接加在y上面
print y.add_(x)


 0.6799  0.1859  1.3768
 1.6563  0.6146  1.3275
 0.4393  0.9025  0.8688
 0.6988  1.1053  1.6277
 0.9798  0.6091  1.0265
[torch.FloatTensor of size 5x3]



In [ ]:
# 所有带_的操作都会改变自身，下面都会改变x自身
x.copy_(y)
x.t_()

# Tensor和Numpy

In [29]:
a = torch.ones(5)
print a
# torch 转 numpy
b = a.numpy()
print b


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [30]:
# 改变a, b也随之改变
a.add_(1)
print (a)
print (b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [24]:
# numpy to torch
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print a
print b

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



# 使用GPU

In [25]:
if torch.cuda.is_available():
    print 'GPU'
    x = x.cuda()
    y = y.cuda()
    x + y

**Autograd**

In [56]:
import torch
from torch.autograd import Variable
# 必须加上
x = Variable(torch.Tensor([2]), requires_grad = True)
y = Variable(torch.Tensor([3]), requires_grad = True)
z = 2 * x + 3 * y + 4
# z对x和y进行求导
z.backward()
# 获得z对x和y的导数
print x.grad.data
print y.grad.data


 2
[torch.FloatTensor of size 1]


 3
[torch.FloatTensor of size 1]



In [60]:
x = Variable(torch.ones(2, 2), requires_grad = True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()
# d(out)/dx
print x.grad


Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [64]:
x = torch.randn(4)
print x
print x.mean()
# 范数
print x.norm()


-0.1458
-1.4115
-1.2933
-0.7356
[torch.FloatTensor of size 4]

-0.896536193788
2.05604142999


In [69]:
x = Variable(torch.Tensor([2]), requires_grad = True)
y = x + 2
gradients = torch.FloatTensor([0.01, 0.1, 1])
y.backward(gradients)
print x.grad.data


 0.0100
 0.1000
 1.0000
[torch.FloatTensor of size 3]



# 线性例子

In [5]:
import torch
from torch.autograd import Variable
import torch.nn as nn

# 输入数据 5*3 3维
x = Variable(torch.randn(5, 3))
y = Variable(torch.randn(5, 2))

# 线性层
linear = nn.Linear(in_features = 3, out_features = 2, bias = True)
print ('w:', linear.weight)
print ('b:', linear.bias)

# 损失函数
loss_func = nn.MSELoss()
# 优化方法
optimizer = torch.optim.SGD(linear.parameters(), lr = 0.01)

# 计算前向过程
pred = linear(x)
print pred

# 计算损失
loss = loss_func(pred, y)
print 'loss:', loss.data[0], len(loss.data)

# 反向传播
loss.backward()

# 输出各变量的梯度
print ('dl/dw: ', linear.weight.grad)
print ('dl/db: ', linear.bias.grad)

# 优化1步
optimizer.step()

# 用优化后的参数计算前向过程，并计算loss
pred = linear(x)
loss = loss_func(pred, y)
print 'new loss:', loss.data[0]

('w:', Parameter containing:
 0.2054  0.3019 -0.3009
-0.3893  0.2550  0.4192
[torch.FloatTensor of size 2x3]
)
('b:', Parameter containing:
 0.4565
-0.3095
[torch.FloatTensor of size 2]
)
Variable containing:
 0.0471 -0.5359
 0.0722 -0.3139
 1.2567 -1.4313
 1.0304 -0.1997
 0.2580 -0.8471
[torch.FloatTensor of size 5x2]

loss: 1.4276945591 1
('dl/dw: ', Variable containing:
 0.7673 -0.3724 -0.3653
-0.2288 -0.0993  0.0386
[torch.FloatTensor of size 2x3]
)
('dl/db: ', Variable containing:
 1.0480
-0.5449
[torch.FloatTensor of size 2]
)
new loss: 1.40469074249


# 激活函数
主要是`relu`, `sigmoid`, `tanh`, `softplus`，激活函数输出都是Variable

In [12]:
import torch
import torch.nn.functional as F
import numpy as np

# [-5, 5], steps=10, space相同
x = torch.linspace(13, 10, steps=10)
x = Variable(x)
x_np = x.data.numpy()
y_relu = F.relu(x).data.numpy()
y_sigmoid = F.sigmoid(x).data.numpy()
y_tanh = F.tanh(x).data.numpy()
y_softplus = F.softplus(x).data.numpy()
y_softmax = F.softmax(x).data.numpy()

# 构建数据

In [13]:
import torch
import torch.utils.data as Data
torch.manual_seed(1)    

BATCH_SIZE = 5
x = torch.linspace(1, 10, 10)       # 输入数据
y = torch.linspace(10, 1, 10)       # 输出数据

# 打包成TensorDataset对象,成为标准数据集
torch_dataset = Data.TensorDataset(data_tensor=x, target_tensor=y)
# 创建数据加载器
loader = Data.DataLoader(
    dataset=torch_dataset,      # TensorDataset类型数据集
    batch_size=BATCH_SIZE,      # mini batch size
    shuffle=True,               # 设置随机洗牌
    num_workers=2,              # 加载数据的进程个数
)

for epoch in range(3):   # 训练3轮
    for step, (batch_x, batch_y) in enumerate(loader):  # 每一步
        # 在这里写训练代码...
        print('Epoch: ', epoch, '| Step: ', step, 
              '| batch x: ', batch_x.numpy(), '| batch y: ', batch_y.numpy())

('Epoch: ', 0, '| Step: ', 0, '| batch x: ', array([ 6.,  7.,  2.,  3.,  1.]), '| batch y: ', array([  5.,   4.,   9.,   8.,  10.]))
('Epoch: ', 0, '| Step: ', 1, '| batch x: ', array([  9.,  10.,   4.,   8.,   5.]), '| batch y: ', array([ 2.,  1.,  7.,  3.,  6.]))
('Epoch: ', 1, '| Step: ', 0, '| batch x: ', array([  3.,   4.,   2.,   9.,  10.]), '| batch y: ', array([ 8.,  7.,  9.,  2.,  1.]))
('Epoch: ', 1, '| Step: ', 1, '| batch x: ', array([ 1.,  7.,  8.,  5.,  6.]), '| batch y: ', array([ 10.,   4.,   3.,   6.,   5.]))
('Epoch: ', 2, '| Step: ', 0, '| batch x: ', array([ 3.,  9.,  2.,  6.,  7.]), '| batch y: ', array([ 8.,  2.,  9.,  5.,  4.]))
('Epoch: ', 2, '| Step: ', 1, '| batch x: ', array([ 10.,   4.,   8.,   1.,   5.]), '| batch y: ', array([  1.,   7.,   3.,  10.,   6.]))


# 完整案例

In [20]:
import torch
from torch.autograd import Variable
import torch.utils.data as Data
import torch.nn as nn

'''超参'''
torch.manual_seed(1)
BATCH_SIZE = 5
LEARNING_RATE = 0.01

'''准备数据'''
#train_data_x = torch.linspace(1, 10, 10)
#train_data_y = torch.linspace(10, 1, 10)
train_data_x = torch.randn(5, 3)
train_data_y = torch.randn(5, 2)

# 打包成TensorDataSet对象成为标准数据集
torch_dataset = Data.TensorDataset(
                data_tensor = train_data_x, target_tensor = train_data_y)
# 创建数据加载器
loader = Data.DataLoader(
    dataset = torch_dataset,
    batch_size = BATCH_SIZE,     # mini batch size
    shuffle = True,
    num_workers = 2,               # 加载数据的进程个数
)

'''构建网络结构'''
linear = nn.Linear(in_features = 3, out_features = 2, bias = True)
print 'w: ', linear.weight
print 'b: ', linear.bias

# 如果支持GPU
if torch.cuda.is_available():
    # 将网络中的参数和缓存移到GPU中
    linear = linear.cuda()

'''损失函数和优化方法'''
loss_func = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr = LEARNING_RATE)

'''训练'''
for epoch in range(3):
    for step, (x, y) in enumerate(loader):
        if torch.cuda.is_available():
            # 将训练数据移至GPU显存
            x = Variable(x).cuda()
            y = Variable(y).cuda()
        output = linear(x)              # 预测一下
        loss = loss_func(output, y)     # 损失
        optimizer.zero_grad()           # 清空上一步的梯度缓存
        loss.backward()                 # 计算新梯度，反向传播
        optimizer.step()                # 优化一步
        print('Epoch: ', epoch, '| Step: ', step, 
              '| batch x: ', batch_x.numpy(), '| batch y: ', batch_y.numpy())


w:  Parameter containing:
 0.4366 -0.3123 -0.5457
 0.0397  0.1968  0.4780
[torch.FloatTensor of size 2x3]

b:  Parameter containing:
1.00000e-02 *
 -9.5488
 -4.9416
[torch.FloatTensor of size 2]



RuntimeError: save_for_backward can only save input or output tensors, but argument 0 doesn't satisfy this condition